name: docker-compose-mysql

services:
  mysqlservice:
    image: mysql:8.0
    container_name: mysql_compose_container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestdb
      MYSQL_USER: jdeveloper
      MYSQL_PASSWORD: jdeveloper
      TZ: Asia/Seoul
    ports:
      - "3307:3306"

    volumes:
      - mysql_volume:/var/lib/mysql
      - ./001.mysql-init.sql:/docker-entrypoint-initdb.d/001.mysql-init.sql
     # ★ MySQL 실행 시 추가 옵션 설정
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
volumes:
  mysql_volume: {}
